import type { HostedChatCommand, HostedCommandPolicy } from "@gradivus/chat/protocol";

const ALL_STATES = ["stopped", "starting", "ready", "running", "stopping", "error"] as const;
const READY_OR_RUNNING = ["ready", "running"] as const;
const READY_ONLY = ["ready"] as const;
const RUNNING_ONLY = ["running"] as const;
const RESUMABLE_STATES = ["stopped", "error"] as const;
const STOPPABLE_STATES = ["starting", "ready", "running", "error"] as const;
const RESTARTABLE_STATES = ["stopped", "ready", "running", "error"] as const;
const NO_STATES = [] as const;

export const CHAT_COMMAND_POLICY = {
	bootstrap: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: false,
		surface: null,
		allowedStates: NO_STATES,
		confirmation: "none",
		payloadType: "HostedChatPayload<'bootstrap'>",
		resultType: "HostedBootstrapSnapshot",
		validator: "empty payload",
		projector: "projectHostedBootstrap",
	},
	createInWorkspace: {
		requiredScopes: ["sessions.manage"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: false,
		surface: null,
		allowedStates: NO_STATES,
		confirmation: "none",
		payloadType: "HostedChatPayload<'createInWorkspace'>",
		resultType: "HostedSessionSnapshot",
		validator: "opaque workspace id and SessionKind",
		projector: "projectHostedSession",
	},
	chooseWorkspaceAndCreate: {
		requiredScopes: ["sessions.manage", "desktop.present"],
		requiresActiveGrant: true,
		requiresDesktopPresent: true,
		requiresSession: false,
		surface: null,
		allowedStates: NO_STATES,
		confirmation: "desktop",
		payloadType: "HostedChatPayload<'chooseWorkspaceAndCreate'>",
		resultType: "HostedNativeActionResult",
		validator: "pathless SessionKind",
		projector: "projectHostedSession",
	},
	openSession: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: ALL_STATES,
		confirmation: "none",
		payloadType: "HostedChatPayload<'openSession'>",
		resultType: "HostedSessionSnapshot",
		validator: "DesktopHost.openSession",
		projector: "projectHostedSession",
	},
	resume: {
		requiredScopes: ["sessions.manage"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: RESUMABLE_STATES,
		confirmation: "none",
		payloadType: "HostedChatPayload<'resume'>",
		resultType: "HostedSessionSnapshot",
		validator: "DesktopHost.resume",
		projector: "projectHostedSession",
	},
	stop: {
		requiredScopes: ["sessions.manage"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: STOPPABLE_STATES,
		confirmation: "none",
		payloadType: "HostedChatPayload<'stop'>",
		resultType: "HostedSessionSnapshot",
		validator: "DesktopHost.stop",
		projector: "projectHostedSession",
	},
	restart: {
		requiredScopes: ["sessions.manage"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: RESTARTABLE_STATES,
		confirmation: "none",
		payloadType: "HostedChatPayload<'restart'>",
		resultType: "HostedSessionSnapshot",
		validator: "DesktopHost.restart",
		projector: "projectHostedSession",
	},
	rename: {
		requiredScopes: ["sessions.manage"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: ALL_STATES,
		confirmation: "none",
		payloadType: "HostedChatPayload<'rename'>",
		resultType: "HostedSessionSnapshot",
		validator: "DesktopHost.rename",
		projector: "projectHostedSession",
	},
	deleteSession: {
		requiredScopes: ["sessions.manage"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: ALL_STATES,
		confirmation: "object-delete",
		payloadType: "HostedChatPayload<'deleteSession'>",
		resultType: "HostedBootstrapSnapshot",
		validator: "current session id and title confirmation",
		projector: "projectHostedBootstrap",
	},
	loadTimelinePage: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: ALL_STATES,
		confirmation: "none",
		payloadType: "HostedChatPayload<'loadTimelinePage'>",
		resultType: "HostedTimelinePage",
		validator: "DesktopHost.loadTimelinePage",
		projector: "projectHostedTimelinePage",
	},
	loadTimelineItem: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: ALL_STATES,
		confirmation: "none",
		payloadType: "HostedChatPayload<'loadTimelineItem'>",
		resultType: "HostedTimelineItem",
		validator: "DesktopHost.loadTimelineItem",
		projector: "projectHostedTimelineItem",
	},
	loadTimelineToolDetail: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: ALL_STATES,
		confirmation: "none",
		payloadType: "HostedChatPayload<'loadTimelineToolDetail'>",
		resultType: "HostedTimelineToolActivity",
		validator: "DesktopHost.loadTimelineToolDetail",
		projector: "projectHostedTimelineToolDetail",
	},
	stagePromptText: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'stagePromptText'>",
		resultType: "HostedPromptAttachmentView",
		validator: "MAX_TEMP_PROMPT_BYTES and grant/session capability",
		projector: "projectHostedPromptAttachment",
	},
	stagePromptAttachments: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "multipart attachment payload",
		resultType: "HostedPromptAttachmentView[]",
		validator: "MAX_PROMPT_ATTACHMENT_* and grant/session capability",
		projector: "projectHostedPromptAttachments",
	},
	releasePromptAttachments: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'releasePromptAttachments'>",
		resultType: "null",
		validator: "grant/session attachment capability",
		projector: "projectHostedVoid",
	},
	prompt: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'prompt'>",
		resultType: "{ requestId: string }",
		validator: "DesktopHost.prompt composition",
		projector: "projectHostedPromptResult",
	},
	editMessage: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'editMessage'>",
		resultType: "HostedEditMessageResult",
		validator: "DesktopHost.editMessage",
		projector: "projectHostedEditMessage",
	},
	abort: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: RUNNING_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'abort'>",
		resultType: "null",
		validator: "DesktopHost.abort",
		projector: "projectHostedVoid",
	},
	steer: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: RUNNING_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'steer'>",
		resultType: "null",
		validator: "DesktopHost.steer composition",
		projector: "projectHostedVoid",
	},
	steerQueued: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: RUNNING_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'steerQueued'>",
		resultType: "null",
		validator: "DesktopHost.steerQueued composition",
		projector: "projectHostedVoid",
	},
	queueFollowUp: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: RUNNING_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'queueFollowUp'>",
		resultType: "null",
		validator: "DesktopHost.queueFollowUp composition",
		projector: "projectHostedVoid",
	},
	getAvailableCommands: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'getAvailableCommands'>",
		resultType: "HostedSlashCommand[]",
		validator: "DesktopHost.getAvailableCommands",
		projector: "projectHostedCommands",
	},
	getAvailableModels: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'getAvailableModels'>",
		resultType: "HostedModelOption[]",
		validator: "DesktopHost.getAvailableModels",
		projector: "projectHostedModels",
	},
	getOpenRouterModelRouting: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'getOpenRouterModelRouting'>",
		resultType: "HostedOpenRouterModelRouting",
		validator: "DesktopHost.getOpenRouterModelRouting",
		projector: "projectHostedOpenRouterRouting",
	},
	setOpenRouterProviderEnabled: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'setOpenRouterProviderEnabled'>",
		resultType: "HostedOpenRouterModelRouting",
		validator: "DesktopHost.setOpenRouterProviderEnabled",
		projector: "projectHostedOpenRouterRouting",
	},
	compact: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'compact'>",
		resultType: "HostedContextMutationResult",
		validator: "DesktopHost.compact",
		projector: "projectHostedContextMutation",
	},
	handoff: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'handoff'>",
		resultType: "HostedContextMutationResult",
		validator: "DesktopHost.handoff",
		projector: "projectHostedContextMutation",
	},
	retry: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'retry'>",
		resultType: "{ started: boolean }",
		validator: "DesktopHost.retry",
		projector: "projectHostedRetry",
	},
	abortRetry: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'abortRetry'>",
		resultType: "null",
		validator: "DesktopHost.abortRetry",
		projector: "projectHostedVoid",
	},
	getSessionStats: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'getSessionStats'>",
		resultType: "HostedSessionStats",
		validator: "DesktopHost.getSessionStats",
		projector: "projectHostedStats",
	},
	exportHtml: {
		requiredScopes: ["chat.read", "desktop.present"],
		requiresActiveGrant: true,
		requiresDesktopPresent: true,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "desktop",
		payloadType: "HostedChatPayload<'exportHtml'>",
		resultType: "HostedExportResult",
		validator: "pathless DesktopHost.exportHtml",
		projector: "projectHostedExport",
	},
	requestPlanReview: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'requestPlanReview'>",
		resultType: "HostedPlanReview",
		validator: "DesktopHost.requestPlanReview",
		projector: "projectHostedPlanReview",
	},
	updatePlanReview: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'updatePlanReview'>",
		resultType: "HostedPlanReview",
		validator: "DesktopHost.updatePlanReview revision",
		projector: "projectHostedPlanReview",
	},
	resolvePlanReview: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'resolvePlanReview'>",
		resultType: "HostedPlanReviewResolution",
		validator: "DesktopHost.resolvePlanReview revision and decision",
		projector: "projectHostedPlanResolution",
	},
	setTodos: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'setTodos'>",
		resultType: "HostedTodoState",
		validator: "DesktopHost.setTodos revision and bounds",
		projector: "projectHostedTodoState",
	},
	setModel: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'setModel'>",
		resultType: "null",
		validator: "DesktopHost.setModel",
		projector: "projectHostedVoid",
	},
	setThinking: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'setThinking'>",
		resultType: "null",
		validator: "DesktopHost.setThinking",
		projector: "projectHostedVoid",
	},
	setFastMode: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'setFastMode'>",
		resultType: "null",
		validator: "DesktopHost.setFastMode",
		projector: "projectHostedVoid",
	},
	togglePlanMode: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'togglePlanMode'>",
		resultType: "HostedSessionRuntimeConfig['planMode']",
		validator: "DesktopHost.togglePlanMode",
		projector: "projectHostedPlanMode",
	},
	setQueueMode: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'setQueueMode'>",
		resultType: "null",
		validator: "DesktopHost.setQueueMode",
		projector: "projectHostedVoid",
	},
	setInterruptMode: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'setInterruptMode'>",
		resultType: "null",
		validator: "DesktopHost.setInterruptMode",
		projector: "projectHostedVoid",
	},
	setAutoCompaction: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'setAutoCompaction'>",
		resultType: "null",
		validator: "DesktopHost.setAutoCompaction",
		projector: "projectHostedVoid",
	},
	setAutoRetry: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'setAutoRetry'>",
		resultType: "null",
		validator: "DesktopHost.setAutoRetry",
		projector: "projectHostedVoid",
	},
	getSubagentMessages: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'getSubagentMessages'>",
		resultType: "HostedAgentHubMessagePage",
		validator: "DesktopHost.getSubagentMessages",
		projector: "projectHostedAgentHubMessages",
	},
	getAgentHub: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'getAgentHub'>",
		resultType: "HostedAgentHubSnapshot",
		validator: "DesktopHost.getAgentHub",
		projector: "projectHostedAgentHub",
	},
	getAgentHubMessages: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'getAgentHubMessages'>",
		resultType: "HostedAgentHubMessagePage",
		validator: "DesktopHost.getAgentHubMessages",
		projector: "projectHostedAgentHubMessages",
	},
	agentHubMessage: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'agentHubMessage'>",
		resultType: "null",
		validator: "DesktopHost.agentHubMessage bounds",
		projector: "projectHostedVoid",
	},
	agentHubKill: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'agentHubKill'>",
		resultType: "null",
		validator: "DesktopHost.agentHubKill",
		projector: "projectHostedVoid",
	},
	agentHubClear: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'agentHubClear'>",
		resultType: "null",
		validator: "DesktopHost.agentHubClear",
		projector: "projectHostedVoid",
	},
	agentHubRevive: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'agentHubRevive'>",
		resultType: "null",
		validator: "DesktopHost.agentHubRevive",
		projector: "projectHostedVoid",
	},
	loadFileDiff: {
		requiredScopes: ["chat.read", "files.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'loadFileDiff'>",
		resultType: "HostedFileView",
		validator: "DesktopHost.loadFileDiff relative in-root target",
		projector: "projectHostedFileDiff",
	},
	loadWorkspaceImage: {
		requiredScopes: ["chat.read", "files.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'loadWorkspaceImage'>",
		resultType: "HostedFileView",
		validator: "DesktopHost.loadWorkspaceImage relative in-root target",
		projector: "projectHostedImage",
	},
	openWorkspaceFile: {
		requiredScopes: ["files.read", "desktop.present"],
		requiresActiveGrant: true,
		requiresDesktopPresent: true,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "desktop",
		payloadType: "HostedChatPayload<'openWorkspaceFile'>",
		resultType: "HostedNativeActionResult",
		validator: "fresh in-root resolution without browser path authority",
		projector: "projectHostedDesktopAction",
	},
	getAgentSettings: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'getAgentSettings'>",
		resultType: "HostedAgentSetting[]",
		validator: "DesktopHost.getAgentSettings",
		projector: "projectHostedAgentSettings",
	},
	setAgentSetting: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'setAgentSetting'>",
		resultType: "HostedAgentSetting",
		validator: "DesktopHost.setAgentSetting",
		projector: "projectHostedAgentSetting",
	},
	getAgentPrompts: {
		requiredScopes: ["chat.read"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_OR_RUNNING,
		confirmation: "none",
		payloadType: "HostedChatPayload<'getAgentPrompts'>",
		resultType: "HostedAgentPrompt[]",
		validator: "DesktopHost.getAgentPrompts",
		projector: "projectHostedAgentPrompts",
	},
	saveAgentPrompt: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'saveAgentPrompt'>",
		resultType: "HostedAgentPrompt",
		validator: "DesktopHost.saveAgentPrompt revision and bounds",
		projector: "projectHostedAgentPrompt",
	},
	resetAgentPrompt: {
		requiredScopes: ["agent.execute"],
		requiresActiveGrant: true,
		requiresDesktopPresent: false,
		requiresSession: true,
		surface: "chat",
		allowedStates: READY_ONLY,
		confirmation: "none",
		payloadType: "HostedChatPayload<'resetAgentPrompt'>",
		resultType: "HostedAgentPrompt",
		validator: "DesktopHost.resetAgentPrompt revision",
		projector: "projectHostedAgentPrompt",
	},
	reconnectRuntime: {
		requiredScopes: ["sessions.manage", "desktop.present"],
		requiresActiveGrant: true,
		requiresDesktopPresent: true,
		requiresSession: false,
		surface: null,
		allowedStates: NO_STATES,
		confirmation: "desktop",
		payloadType: "HostedChatPayload<'reconnectRuntime'>",
		resultType: "HostedNativeActionResult",
		validator: "local runtime unavailable",
		projector: "projectHostedDesktopAction",
	},
	openDesktopAccounts: {
		requiredScopes: ["desktop.present"],
		requiresActiveGrant: true,
		requiresDesktopPresent: true,
		requiresSession: false,
		surface: null,
		allowedStates: NO_STATES,
		confirmation: "desktop",
		payloadType: "HostedChatPayload<'openDesktopAccounts'>",
		resultType: "HostedNativeActionResult",
		validator: "Desktop Accounts focus",
		projector: "projectHostedDesktopAction",
	},
} satisfies Record<HostedChatCommand["operation"], HostedCommandPolicy>;
