import { describe, expect, test } from "bun:test";
import { Settings } from "@oh-my-pi/pi-coding-agent/config/settings";
import { getRpcSettings, setRpcSetting } from "@oh-my-pi/pi-coding-agent/modes/rpc/rpc-settings";
import type { SamplingParameters } from "@oh-my-pi/pi-coding-agent/session/agent-session";
import type { ToolSession } from "@oh-my-pi/pi-coding-agent/tools";
import { BashTool } from "@oh-my-pi/pi-coding-agent/tools/bash";

const EXPECTED_RPC_PATHS = [
	"images.autoResize",
	"images.blockImages",
	"images.describeForTextModels",
	"includeModelInPrompt",
	"personality",
	"temperature",
	"retry.maxRetries",
	"retry.modelFallback",
	"retry.usageAwareFallback",
	"retry.fallbackRevertPolicy",
	"compaction.midTurnEnabled",
	"compaction.methodOrder",
	"compaction.supersedeReads",
	"compaction.dropUseless",
	"compaction.enabled",
	"tools.approvalMode",
	"todo.enabled",
	"launch.enabled",
	"generate_image.enabled",
	"inspect_image.mode",
	"tools.intentTracing",
	"tools.abortOnFabricatedResult",
	"async.enabled",
	"tools.xdev",
	"tools.xdevDocs",
	"plan.enabled",
	"goal.enabled",
	"task.eager",
	"task.batch",
	"task.enableEffort",
	"task.maxConcurrency",
	"task.enableLsp",
	"modelRoleStorage",
	"defaultThinkingLevel",
	"advisor.enabled",
	"omitThinking",
	"externalThinking",
	"model.loopGuard.enabled",
	"model.loopGuard.checkAssistantContent",
	"model.loopGuard.toolCallReminder",
	"model.toolCallLoopGuard.enabled",
	"inlineToolDescriptors",
	"includeWorkspaceTree",
	"topP",
	"topK",
	"minP",
	"presencePenalty",
	"repetitionPenalty",
	"textVerbosity",
	"prewalk.enabled",
	"steeringMode",
	"followUpMode",
	"interruptMode",
	"magicKeywords.enabled",
	"magicKeywords.ultrathink",
	"magicKeywords.orchestrate",
	"magicKeywords.workflow",
	"features.unexpectedStopDetection",
	"contextPromotion.enabled",
	"compaction.handoffSaveToDisk",
	"snapcompact.systemPrompt",
	"snapcompact.toolResults",
	"snapcompact.shape",
	"tools.format",
	"edit.mode",
	"edit.fuzzyMatch",
	"edit.fuzzyThreshold",
	"edit.streamingAbort",
	"edit.blockAutoGenerated",
	"edit.enforceSeenLines",
	"readLineNumbers",
	"read.defaultLimit",
	"read.renderMarkdown",
	"read.summarize.enabled",
	"read.summarize.prose",
	"read.toolResultPreview",
	"lsp.enabled",
	"lsp.lazy",
	"lsp.shared",
	"lsp.formatOnWrite",
	"lsp.diagnosticsOnWrite",
	"lsp.diagnosticsOnEdit",
	"lsp.diagnosticsDeduplicate",
	"bash.enabled",
	"bash.autoBackground.enabled",
	"bashInterceptor.enabled",
	"bash.direnv",
	"shellMinimizer.enabled",
	"shellMinimizer.sourceOutlineLevel",
	"eval.py",
	"eval.js",
	"eval.rb",
	"eval.jl",
	"python.kernelMode",
	"tools.artifactSpillThreshold",
	"tools.artifactTailBytes",
	"tools.artifactHeadBytes",
	"tools.outputMaxColumns",
	"tools.artifactTailLines",
	"todo.reminders",
	"todo.remindersMax",
	"grep.contextBefore",
	"grep.contextAfter",
	"inspect_image.timeoutMs",
	"computer.enabled",
	"fetch.enabled",
	"security.enabled",
	"tools.maxTimeout",
	"async.pollWaitDuration",
	"irc.timeoutMs",
	"mcp.renderMarkdownResults",
	"task.maxRecursionDepth",
	"task.maxRuntimeMs",
	"task.softRequestBudget",
	"task.softRequestBudgetNotice",
	"task.maxEffort",
] as const;

function schemaExpression(tool: BashTool): string {
	const parameters = tool.parameters;
	if (!("expression" in parameters) || typeof parameters.expression !== "string") {
		throw new Error("Expected an ArkType schema expression");
	}
	return parameters.expression;
}

describe("RPC settings", () => {
	test("lists curated scalar settings with finite controls", () => {
		const settings = getRpcSettings(Settings.isolated());

		expect(settings.length).toBeGreaterThanOrEqual(30);
		expect(settings.find(setting => setting.path === "generate_image.enabled")).toMatchObject({
			label: "Generate Image",
			control: "toggle",
			value: false,
			apply: "next-session",
		});
		expect(settings.find(setting => setting.path === "personality")?.options?.map(option => option.value)).toEqual([
			"default",
			"friendly",
			"pragmatic",
			"none",
		]);
		expect(settings.every(setting => setting.control === "toggle" || (setting.options?.length ?? 0) > 0)).toBe(true);
	});

	test("exposes exactly the curated credential-safe path set", () => {
		const settings = getRpcSettings(Settings.isolated());
		expect(settings.map(setting => setting.path)).toEqual([...EXPECTED_RPC_PATHS]);
		expect(new Set(settings.map(setting => setting.path)).size).toBe(EXPECTED_RPC_PATHS.length);
		expect(settings.every(setting => !["memory", "providers"].includes(String(setting.tab)))).toBe(true);
	});

	test("exposes the expanded finite scalar catalog without memory or provider settings", () => {
		const settings = getRpcSettings(Settings.isolated());
		const byPath = new Map(settings.map(setting => [setting.path, setting]));
		for (const path of [
			"modelRoleStorage",
			"defaultThinkingLevel",
			"model.loopGuard.toolCallReminder",
			"compaction.enabled",
			"edit.fuzzyThreshold",
			"lsp.enabled",
			"bash.enabled",
			"tools.artifactTailBytes",
			"task.maxRuntimeMs",
		]) {
			expect(byPath.has(path)).toBe(true);
		}
		expect(settings.filter(setting => setting.tab === "files" || setting.tab === "shell").length).toBeGreaterThan(0);
		expect(settings.some(setting => ["memory", "providers"].includes(String(setting.tab)))).toBe(false);
		expect(byPath.get("edit.mode")?.apply).toBe("next-session");
		expect(byPath.get("inlineToolDescriptors")?.apply).toBe("next-session");
		expect(byPath.get("todo.enabled")?.apply).toBe("next-session");
		expect(byPath.get("tools.maxTimeout")?.apply).toBe("immediate");
		expect(byPath.get("compaction.handoffSaveToDisk")?.apply).toBe("immediate");
	});

	test("round-trips finite numeric and string options with original types", async () => {
		const settings = Settings.isolated();
		const session = {
			settings,
			refreshBaseSystemPrompt: async () => undefined,
			applyInspectImageModeChange: async () => true,
		};
		const numeric = getRpcSettings(settings).find(setting => setting.path === "edit.fuzzyThreshold");
		const numericOption = numeric?.options?.find(
			option => typeof option.value === "number" && !Object.is(option.value, numeric.value),
		);
		if (!numericOption || typeof numericOption.value !== "number")
			throw new Error("Expected a numeric fuzzy-threshold option");
		const numericResult = await setRpcSetting(session, "edit.fuzzyThreshold", numericOption.value);
		expect(numericResult.value).toBe(numericOption.value);
		expect(typeof numericResult.value).toBe("number");

		const stringResult = await setRpcSetting(session, "personality", "friendly");
		expect(stringResult.value).toBe("friendly");
		expect(typeof stringResult.value).toBe("string");
	});

	test("applies named live effects and keeps construction-captured settings next-session only", async () => {
		const settings = Settings.isolated();
		const calls: string[] = [];
		const session = {
			settings,
			refreshBaseSystemPrompt: async () => undefined,
			applyInspectImageModeChange: async () => true,
			setThinkingLevel: () => calls.push("thinking"),
			setAdvisorEnabled: () => {
				calls.push("advisor");
				return true;
			},
			setOmitThinking: () => calls.push("omit"),
			setThinkToolEnabled: async () => {
				calls.push("think");
				return true;
			},
			setSamplingParameters: (parameters: SamplingParameters) =>
				calls.push(`sampling:${Object.keys(parameters)[0]}`),
			setSteeringMode: () => calls.push("steering"),
			setFollowUpMode: () => calls.push("follow-up"),
			setInterruptMode: () => calls.push("interrupt"),
			setAutoCompactionEnabled: () => calls.push("compaction"),
			setComputerToolEnabled: async () => {
				calls.push("computer");
				return true;
			},
		};

		await setRpcSetting(session, "defaultThinkingLevel", "low");
		await setRpcSetting(session, "advisor.enabled", true);
		await setRpcSetting(session, "omitThinking", true);
		await setRpcSetting(session, "externalThinking", true);
		const temperature = getRpcSettings(settings).find(setting => setting.path === "temperature");
		const temperatureOption = temperature?.options?.find(option => typeof option.value === "number");
		if (!temperatureOption || typeof temperatureOption.value !== "number")
			throw new Error("Expected a temperature option");
		await setRpcSetting(session, "temperature", temperatureOption.value);
		await setRpcSetting(session, "computer.enabled", !settings.get("computer.enabled"));
		await setRpcSetting(session, "compaction.enabled", !settings.get("compaction.enabled"));
		await setRpcSetting(session, "steeringMode", "all");
		await setRpcSetting(session, "followUpMode", "all");
		await setRpcSetting(session, "interruptMode", "wait");
		expect(calls).toEqual([
			"thinking",
			"advisor",
			"omit",
			"think",
			"sampling:temperature",
			"computer",
			"compaction",
			"steering",
			"follow-up",
			"interrupt",
		]);

		const inline = getRpcSettings(settings).find(setting => setting.path === "inlineToolDescriptors");
		const nextValue = inline?.options?.find(option => !Object.is(option.value, inline.value))?.value;
		if (nextValue === undefined) throw new Error("inlineToolDescriptors has no alternate finite option");
		await setRpcSetting(session, "inlineToolDescriptors", nextValue);
		expect(calls).toHaveLength(10);
	});

	test("next-session settings leave constructed tools unchanged and reach new tools", async () => {
		const settings = Settings.isolated();
		const session = {
			settings,
			refreshBaseSystemPrompt: async () => undefined,
			applyInspectImageModeChange: async () => true,
		};
		const toolSession = {
			cwd: "/tmp",
			hasUI: false,
			getSessionFile: () => null,
			settings,
		} as unknown as ToolSession;
		const currentTool = new BashTool(toolSession);
		const currentExpression = schemaExpression(currentTool);
		expect(currentExpression).toContain("async?: boolean");

		await setRpcSetting(session, "async.enabled", false);
		expect(schemaExpression(currentTool)).toBe(currentExpression);

		const nextTool = new BashTool(toolSession);
		const nextExpression = schemaExpression(nextTool);
		expect(nextExpression).not.toContain("async?: boolean");
		expect(settings.get("async.enabled")).toBe(false);
	});

	test("rejects false tool effects and rolls settings back", async () => {
		const settings = Settings.isolated();
		const calls: boolean[] = [];
		const session = {
			settings,
			refreshBaseSystemPrompt: async () => undefined,
			applyInspectImageModeChange: async () => true,
			setThinkToolEnabled: async (enabled: boolean) => {
				calls.push(enabled);
				return !enabled;
			},
		};

		await expect(setRpcSetting(session, "externalThinking", true)).rejects.toThrow("could not be applied");

		const computerSettings = Settings.isolated({ "computer.enabled": false });
		const computerCalls: boolean[] = [];
		const computerSession = {
			settings: computerSettings,
			refreshBaseSystemPrompt: async () => undefined,
			applyInspectImageModeChange: async () => true,
			setComputerToolEnabled: async (enabled: boolean) => {
				computerCalls.push(enabled);
				return false;
			},
		};
		await expect(setRpcSetting(computerSession, "computer.enabled", true)).rejects.toThrow("could not be applied");
		expect(computerSettings.get("computer.enabled")).toBe(false);
		expect(computerCalls).toEqual([true, false]);
		expect(settings.get("externalThinking")).toBe(false);
		expect(calls).toEqual([true, false]);
	});

	test("rolls back a setting and its effect when application throws", async () => {
		const settings = Settings.isolated();
		const calls: string[] = [];
		const session = {
			settings,
			refreshBaseSystemPrompt: async () => {
				calls.push(String(settings.get("personality")));
				throw new Error("prompt refresh failed");
			},
			applyInspectImageModeChange: async () => true,
		};

		await expect(setRpcSetting(session, "personality", "friendly")).rejects.toThrow("prompt refresh failed");
		expect(settings.get("personality")).toBe("default");
		expect(calls).toEqual(["friendly", "default"]);
	});

	test("validates mutations and applies live prompt and vision side effects", async () => {
		const settings = Settings.isolated();
		let promptRefreshes = 0;
		let visionRefreshes = 0;
		const session = {
			settings,
			refreshBaseSystemPrompt: async () => {
				promptRefreshes++;
			},
			applyInspectImageModeChange: async () => {
				visionRefreshes++;
				return true;
			},
		};

		const personality = await setRpcSetting(session, "personality", "pragmatic");
		expect(personality.value).toBe("pragmatic");
		expect(settings.get("personality")).toBe("pragmatic");
		expect(promptRefreshes).toBe(1);

		await setRpcSetting(session, "inspect_image.mode", "on");
		expect(settings.get("inspect_image.mode")).toBe("on");
		expect(visionRefreshes).toBe(1);

		await expect(setRpcSetting(session, "personality", "reckless")).rejects.toThrow("not a supported value");
		await expect(setRpcSetting(session, "auth.apiKey", "secret")).rejects.toThrow("not available over RPC");
	});
});
