import { WORKSPACE_MAX_EVENT_BATCH, WORKSPACE_MAX_PANES, WORKSPACE_WIRE_VERSION } from "@oh-my-pi/pi-wire";

export const WORKSPACE_RUNTIME_VERSION = 2 as const;
export const MAX_WORKSPACE_PANES = WORKSPACE_MAX_PANES;
export const MAX_WORKSPACE_EVENTS = WORKSPACE_MAX_EVENT_BATCH;
export const MAX_WORKSPACE_COMMANDS = WORKSPACE_MAX_EVENT_BATCH;
export const WORKSPACE_MIN_RATIO = 20;
export const WORKSPACE_MAX_RATIO = 80;
export const WORKSPACE_PROTOCOL_V1 = `workspace.v${WORKSPACE_WIRE_VERSION}`;
export const WORKSPACE_COMMAND_CAP_V1 = MAX_WORKSPACE_COMMANDS;
export const WORKSPACE_PROTOCOL_VERSION = WORKSPACE_WIRE_VERSION;
export const MAX_WORKSPACE_COMMAND_BATCH = MAX_WORKSPACE_COMMANDS;
export const MAX_WORKSPACE_EVENT_BATCH = MAX_WORKSPACE_EVENTS;
export const WORKSPACE_EVENT_CAP_V1 = MAX_WORKSPACE_EVENTS;
